### ISSUE TITLE
Conversion to Gregorian is 2 years off

### ISSUE THREAD

**Issue by alfclement** [jonbleiberg88/mayacal#3]
Try this example:

```
gd = mc.utils.GregorianDate(10,1,2022)
print(gd, end='   ')
r = gd.to_mayadate()
print(r)
lc = mc.LongCount(13,0,9,3,7)
print(lc)
print(lc.to_gregorian())

```
Output:
Jan 10, 2022 CE   13.0.9.3.7  9 Manik 5 Muwan
13.0.9.3.7
Jan 10, **2020** CE

**Comment by jonbleiberg88** [comment]
Hi @alfclement - thanks for submitting this!

I'll try to take a look as soon as I can (feel free to submit a PR in the meantime if you'd like!)
